/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package open62Wrap;

public interface open62541Constants {
  public final static int UA_ACCESSLEVELMASK_READ = open62541JNI.UA_ACCESSLEVELMASK_READ_get();
  public final static int UA_ACCESSLEVELMASK_WRITE = open62541JNI.UA_ACCESSLEVELMASK_WRITE_get();
  public final static int UA_ACCESSLEVELMASK_HISTORYREAD = open62541JNI.UA_ACCESSLEVELMASK_HISTORYREAD_get();
  public final static int UA_ACCESSLEVELMASK_HISTORYWRITE = open62541JNI.UA_ACCESSLEVELMASK_HISTORYWRITE_get();
  public final static int UA_ACCESSLEVELMASK_SEMANTICCHANGE = open62541JNI.UA_ACCESSLEVELMASK_SEMANTICCHANGE_get();
  public final static int UA_ACCESSLEVELMASK_STATUSWRITE = open62541JNI.UA_ACCESSLEVELMASK_STATUSWRITE_get();
  public final static int UA_ACCESSLEVELMASK_TIMESTAMPWRITE = open62541JNI.UA_ACCESSLEVELMASK_TIMESTAMPWRITE_get();
  public final static int UA_TYPES_BOOLEAN = open62541JNI.UA_TYPES_BOOLEAN_get();
  public final static int UA_TYPES_SBYTE = open62541JNI.UA_TYPES_SBYTE_get();
  public final static int UA_TYPES_BYTE = open62541JNI.UA_TYPES_BYTE_get();
  public final static int UA_TYPES_INT16 = open62541JNI.UA_TYPES_INT16_get();
  public final static int UA_TYPES_UINT16 = open62541JNI.UA_TYPES_UINT16_get();
  public final static int UA_TYPES_INT32 = open62541JNI.UA_TYPES_INT32_get();
  public final static int UA_TYPES_UINT32 = open62541JNI.UA_TYPES_UINT32_get();
  public final static int UA_TYPES_INT64 = open62541JNI.UA_TYPES_INT64_get();
  public final static int UA_TYPES_UINT64 = open62541JNI.UA_TYPES_UINT64_get();
  public final static int UA_TYPES_FLOAT = open62541JNI.UA_TYPES_FLOAT_get();
  public final static int UA_TYPES_DOUBLE = open62541JNI.UA_TYPES_DOUBLE_get();
  public final static int UA_TYPES_STRING = open62541JNI.UA_TYPES_STRING_get();
  public final static int UA_TYPES_DATETIME = open62541JNI.UA_TYPES_DATETIME_get();
  public final static int UA_TYPES_GUID = open62541JNI.UA_TYPES_GUID_get();
  public final static int UA_TYPES_BYTESTRING = open62541JNI.UA_TYPES_BYTESTRING_get();
  public final static int UA_TYPES_XMLELEMENT = open62541JNI.UA_TYPES_XMLELEMENT_get();
  public final static int UA_TYPES_NODEID = open62541JNI.UA_TYPES_NODEID_get();
  public final static int UA_TYPES_EXPANDEDNODEID = open62541JNI.UA_TYPES_EXPANDEDNODEID_get();
  public final static int UA_TYPES_STATUSCODE = open62541JNI.UA_TYPES_STATUSCODE_get();
  public final static int UA_TYPES_QUALIFIEDNAME = open62541JNI.UA_TYPES_QUALIFIEDNAME_get();
  public final static int UA_TYPES_LOCALIZEDTEXT = open62541JNI.UA_TYPES_LOCALIZEDTEXT_get();
  public final static int UA_TYPES_EXTENSIONOBJECT = open62541JNI.UA_TYPES_EXTENSIONOBJECT_get();
  public final static int UA_TYPES_DATAVALUE = open62541JNI.UA_TYPES_DATAVALUE_get();
  public final static int UA_TYPES_VARIANT = open62541JNI.UA_TYPES_VARIANT_get();
  public final static int UA_TYPES_DIAGNOSTICINFO = open62541JNI.UA_TYPES_DIAGNOSTICINFO_get();
  public final static int UA_TYPES_KEYVALUEPAIR = open62541JNI.UA_TYPES_KEYVALUEPAIR_get();
  public final static int UA_VALUERANK_SCALAR_OR_ONE_DIMENSION = open62541JNI.UA_VALUERANK_SCALAR_OR_ONE_DIMENSION_get();
  public final static int UA_VALUERANK_ANY = open62541JNI.UA_VALUERANK_ANY_get();
  public final static int UA_VALUERANK_SCALAR = open62541JNI.UA_VALUERANK_SCALAR_get();
  public final static int UA_VALUERANK_ONE_OR_MORE_DIMENSIONS = open62541JNI.UA_VALUERANK_ONE_OR_MORE_DIMENSIONS_get();
  public final static int UA_VALUERANK_ONE_DIMENSION = open62541JNI.UA_VALUERANK_ONE_DIMENSION_get();
  public final static int UA_VALUERANK_TWO_DIMENSIONS = open62541JNI.UA_VALUERANK_TWO_DIMENSIONS_get();
  public final static int UA_VALUERANK_THREE_DIMENSIONS = open62541JNI.UA_VALUERANK_THREE_DIMENSIONS_get();
}
