/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package open62Wrap;

public class open62541 implements open62541Constants {
  public static UA_NodeId UA_NODEID_NUMERIC(int nsIndex, int identifier) {
    return new UA_NodeId(open62541JNI.UA_NODEID_NUMERIC(nsIndex, identifier), true);
  }

  public static int void2int(long v) {
    return open62541JNI.void2int(v);
  }

  public static String void2str(long v) {
    return open62541JNI.void2str(v);
  }

  public static boolean IsVariantType_Int(UA_Variant variant) {
    return open62541JNI.IsVariantType_Int(UA_Variant.getCPtr(variant), variant);
  }

  public static boolean IsVariantType_String(UA_Variant variant) {
    return open62541JNI.IsVariantType_String(UA_Variant.getCPtr(variant), variant);
  }

  public static SWIGTYPE_p_int new_intp() {
    long cPtr = open62541JNI.new_intp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public static SWIGTYPE_p_int copy_intp(int value) {
    long cPtr = open62541JNI.copy_intp(value);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public static void delete_intp(SWIGTYPE_p_int obj) {
    open62541JNI.delete_intp(SWIGTYPE_p_int.getCPtr(obj));
  }

  public static void intp_assign(SWIGTYPE_p_int obj, int value) {
    open62541JNI.intp_assign(SWIGTYPE_p_int.getCPtr(obj), value);
  }

  public static int intp_value(SWIGTYPE_p_int obj) {
    return open62541JNI.intp_value(SWIGTYPE_p_int.getCPtr(obj));
  }

}
