/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package open62Wrap;

public class UA_DataType {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected UA_DataType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UA_DataType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        open62541JNI.delete_UA_DataType(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTypeId(UA_NodeId value) {
    open62541JNI.UA_DataType_typeId_set(swigCPtr, this, UA_NodeId.getCPtr(value), value);
  }

  public UA_NodeId getTypeId() {
    long cPtr = open62541JNI.UA_DataType_typeId_get(swigCPtr, this);
    return (cPtr == 0) ? null : new UA_NodeId(cPtr, false);
  }

  public void setMemSize(int value) {
    open62541JNI.UA_DataType_memSize_set(swigCPtr, this, value);
  }

  public int getMemSize() {
    return open62541JNI.UA_DataType_memSize_get(swigCPtr, this);
  }

  public void setTypeIndex(int value) {
    open62541JNI.UA_DataType_typeIndex_set(swigCPtr, this, value);
  }

  public int getTypeIndex() {
    return open62541JNI.UA_DataType_typeIndex_get(swigCPtr, this);
  }

  public void setTypeKind(int value) {
    open62541JNI.UA_DataType_typeKind_set(swigCPtr, this, value);
  }

  public int getTypeKind() {
    return open62541JNI.UA_DataType_typeKind_get(swigCPtr, this);
  }

  public void setPointerFree(int value) {
    open62541JNI.UA_DataType_pointerFree_set(swigCPtr, this, value);
  }

  public int getPointerFree() {
    return open62541JNI.UA_DataType_pointerFree_get(swigCPtr, this);
  }

  public void setOverlayable(int value) {
    open62541JNI.UA_DataType_overlayable_set(swigCPtr, this, value);
  }

  public int getOverlayable() {
    return open62541JNI.UA_DataType_overlayable_get(swigCPtr, this);
  }

  public void setMembersSize(int value) {
    open62541JNI.UA_DataType_membersSize_set(swigCPtr, this, value);
  }

  public int getMembersSize() {
    return open62541JNI.UA_DataType_membersSize_get(swigCPtr, this);
  }

  public void setBinaryEncodingId(int value) {
    open62541JNI.UA_DataType_binaryEncodingId_set(swigCPtr, this, value);
  }

  public int getBinaryEncodingId() {
    return open62541JNI.UA_DataType_binaryEncodingId_get(swigCPtr, this);
  }

  public void setMembers(UA_DataTypeMember value) {
    open62541JNI.UA_DataType_members_set(swigCPtr, this, UA_DataTypeMember.getCPtr(value), value);
  }

  public UA_DataTypeMember getMembers() {
    long cPtr = open62541JNI.UA_DataType_members_get(swigCPtr, this);
    return (cPtr == 0) ? null : new UA_DataTypeMember(cPtr, false);
  }

  public UA_DataType() {
    this(open62541JNI.new_UA_DataType(), true);
  }

}
