/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package open62Wrap;

public class UA_Guid {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected UA_Guid(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UA_Guid obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        open62541JNI.delete_UA_Guid(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setData1(int value) {
    open62541JNI.UA_Guid_data1_set(swigCPtr, this, value);
  }

  public int getData1() {
    return open62541JNI.UA_Guid_data1_get(swigCPtr, this);
  }

  public void setData2(int value) {
    open62541JNI.UA_Guid_data2_set(swigCPtr, this, value);
  }

  public int getData2() {
    return open62541JNI.UA_Guid_data2_get(swigCPtr, this);
  }

  public void setData3(int value) {
    open62541JNI.UA_Guid_data3_set(swigCPtr, this, value);
  }

  public int getData3() {
    return open62541JNI.UA_Guid_data3_get(swigCPtr, this);
  }

  public void setData4(SWIGTYPE_p_unsigned_char value) {
    open62541JNI.UA_Guid_data4_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getData4() {
    long cPtr = open62541JNI.UA_Guid_data4_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public UA_Guid() {
    this(open62541JNI.new_UA_Guid(), true);
  }

}
