/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package open62Wrap;

public class UA_LocalizedText {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected UA_LocalizedText(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UA_LocalizedText obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        open62541JNI.delete_UA_LocalizedText(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLocale(String value) {
    open62541JNI.UA_LocalizedText_locale_set(swigCPtr, this, value);
  }

  public String getLocale() {
    return open62541JNI.UA_LocalizedText_locale_get(swigCPtr, this);
  }

  public void setText(String value) {
    open62541JNI.UA_LocalizedText_text_set(swigCPtr, this, value);
  }

  public String getText() {
    return open62541JNI.UA_LocalizedText_text_get(swigCPtr, this);
  }

  public UA_LocalizedText() {
    this(open62541JNI.new_UA_LocalizedText(), true);
  }

}
