/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package open62Wrap;

public class UA_MethodAttributes {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected UA_MethodAttributes(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UA_MethodAttributes obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        open62541JNI.delete_UA_MethodAttributes(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSpecifiedAttributes(int value) {
    open62541JNI.UA_MethodAttributes_specifiedAttributes_set(swigCPtr, this, value);
  }

  public int getSpecifiedAttributes() {
    return open62541JNI.UA_MethodAttributes_specifiedAttributes_get(swigCPtr, this);
  }

  public void setDisplayName(UA_LocalizedText value) {
    open62541JNI.UA_MethodAttributes_displayName_set(swigCPtr, this, UA_LocalizedText.getCPtr(value), value);
  }

  public UA_LocalizedText getDisplayName() {
    long cPtr = open62541JNI.UA_MethodAttributes_displayName_get(swigCPtr, this);
    return (cPtr == 0) ? null : new UA_LocalizedText(cPtr, false);
  }

  public void setDescription(UA_LocalizedText value) {
    open62541JNI.UA_MethodAttributes_description_set(swigCPtr, this, UA_LocalizedText.getCPtr(value), value);
  }

  public UA_LocalizedText getDescription() {
    long cPtr = open62541JNI.UA_MethodAttributes_description_get(swigCPtr, this);
    return (cPtr == 0) ? null : new UA_LocalizedText(cPtr, false);
  }

  public void setWriteMask(int value) {
    open62541JNI.UA_MethodAttributes_writeMask_set(swigCPtr, this, value);
  }

  public int getWriteMask() {
    return open62541JNI.UA_MethodAttributes_writeMask_get(swigCPtr, this);
  }

  public void setUserWriteMask(int value) {
    open62541JNI.UA_MethodAttributes_userWriteMask_set(swigCPtr, this, value);
  }

  public int getUserWriteMask() {
    return open62541JNI.UA_MethodAttributes_userWriteMask_get(swigCPtr, this);
  }

  public void setExecutable(boolean value) {
    open62541JNI.UA_MethodAttributes_executable_set(swigCPtr, this, value);
  }

  public boolean getExecutable() {
    return open62541JNI.UA_MethodAttributes_executable_get(swigCPtr, this);
  }

  public void setUserExecutable(boolean value) {
    open62541JNI.UA_MethodAttributes_userExecutable_set(swigCPtr, this, value);
  }

  public boolean getUserExecutable() {
    return open62541JNI.UA_MethodAttributes_userExecutable_get(swigCPtr, this);
  }

  public UA_MethodAttributes() {
    this(open62541JNI.new_UA_MethodAttributes(), true);
  }

}
