/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package open62Wrap;

public class UA_NodeId {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected UA_NodeId(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UA_NodeId obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        open62541JNI.delete_UA_NodeId(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNamespaceIndex(int value) {
    open62541JNI.UA_NodeId_namespaceIndex_set(swigCPtr, this, value);
  }

  public int getNamespaceIndex() {
    return open62541JNI.UA_NodeId_namespaceIndex_get(swigCPtr, this);
  }

  public void setIdentifierType(UA_NodeIdType value) {
    open62541JNI.UA_NodeId_identifierType_set(swigCPtr, this, value.swigValue());
  }

  public UA_NodeIdType getIdentifierType() {
    return UA_NodeIdType.swigToEnum(open62541JNI.UA_NodeId_identifierType_get(swigCPtr, this));
  }

  public void setIdentifier(Identifier value) {
    open62541JNI.UA_NodeId_identifier_set(swigCPtr, this, Identifier.getCPtr(value), value);
  }

  public Identifier getIdentifier() {
    long cPtr = open62541JNI.UA_NodeId_identifier_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Identifier(cPtr, false);
  }

  public UA_NodeId() {
    this(open62541JNI.new_UA_NodeId(), true);
  }

}
