/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package open62Wrap;

public final class UA_VariantStorageType {
  public final static UA_VariantStorageType UA_VARIANT_DATA = new UA_VariantStorageType("UA_VARIANT_DATA");
  public final static UA_VariantStorageType UA_VARIANT_DATA_NODELETE = new UA_VariantStorageType("UA_VARIANT_DATA_NODELETE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static UA_VariantStorageType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + UA_VariantStorageType.class + " with value " + swigValue);
  }

  private UA_VariantStorageType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private UA_VariantStorageType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private UA_VariantStorageType(String swigName, UA_VariantStorageType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static UA_VariantStorageType[] swigValues = { UA_VARIANT_DATA, UA_VARIANT_DATA_NODELETE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

