package fiab.mes.assembly.monitoring;

import fiab.mes.assembly.monitoring.message.PartsPickedNotification
import ProcessCore.XmlRoot
import ProcessCore.ProcessStep
import fiab.mes.assembly.monitoring.DroolsUtil
import java.util.ArrayList;
import InstanceExtensionModel.States;
import InstanceExtensionModel.StepInstanceExtension;
import fiab.mes.order.OrderProcess;

rule "Cookie to Step Allocation"

    when 
        $event: PartsPickedNotification(partId == "Cookie")
    then
        System.out.println("Cookie was picked and that was the right choice");
        System.out.println($event);

end


rule "Part to Step Allocation"

    when
        $xmlRoot : XmlRoot()
        $orderProc: OrderProcess()
        $event: PartsPickedNotification()
    then
        System.out.println("Hurray!");
        DroolsUtil.activateStepafterPartNotif($xmlRoot, $orderProc, $event.getPartId());

end
